# ╭────────────────────────────────────────────────────────────────────────────────────────────────╮
# │  ACTION REQUIRED: REVIEW AND EDIT THIS FILE TO ENSURE IT ACCURATELY REFLECTS YOUR PROJECT!     ││                                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

# ╭────────────────────────ImplementationGuide-hl7.fhir.us.davinci-pdex.json───────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pdex
canonical: http://hl7.org/fhir/us/davinci-pdex
version: 2.0.0
name: DaVinciPayerDataExchange
title: Da Vinci Payer Data Exchange
status: draft  # draft | active | retired | unknown
publisher:
  name: HL7 International / Financial Management
  url: http://www.hl7.org/Special/committees/fm
  email: fm@lists.HL7.org
contact:
  - name: "Mark Scrimshire (mark.scrimshire@onyxhealth.io)"
    telecom:
      - system: email
        value: "mailto:mark.scrimshire@onyxhealth.io"
  - name: "HL7 International - Financial Management"
    telecom:
      - system: url
        value: "http://www.hl7.org/Special/committees/fm"
description: "This specification has undergone ballot and connectathon testing. It is expected to evolve, possibly significantly, as part of that process.\nFeedback is welcome and may be submitted through the FHIR JIRA tracker indicating US Da Vinci PDex as the specification. If balloting on this IG, please submit your comments via the tracker and reference them in your ballot submission implementation guide.\n\nThis guide can be reviewed offline. Go to the Downloads section. Click on the link to download the full Implementation Guide as a zip file. Expand the zip file and use a web browser to launch the index.html file in the directory created by the zip extract process. External hyperlinks in the guide will not be available unless you have an active internet connection. \n\n[Financial Management](https://confluence.hl7.org/display/FM/Financial+Management+Home) is the Sponsoring Work Group for this Implementation Guide.\n\n**The Payer Data Exchange (PDex) Implementation Guide (IG) is provided for Payers/Health Plans to enable them to create a Member's Health History using clinical resources (based on US Core 3.1.1 Profiles based on FHIR R4) which can be understood by providers and, if they choose to, committed to their Electronic Medical Records (EMR) System.**\n\nThe PDex work group has made changes to the original version of the IG following the publication of the final CMS Interoperability and Patient Access Rule.\n\nThis IG uses the same Member Health History \"payload\" for member-authorized exchange of information with other Health Plans and with Third-Party Applications. It describes the interaction patterns that, when followed, allow the various parties involved in managing healthcare and payer data to more easily integrate and exchange data securely and effectively.\n\nThis IG covers the exchange of:\n- Claims-based information\n- Clinical Information (such as Lab Results, Allergies and Conditions)\n\nThis IG covers the exchange of this information using US Core and Da Vinci Health Record Exchange (HRex) Profiles. This superset of clinical profiles forms the Health Plan Member's Health History. \n\nThis IG covers the exchange of a Member's Health History in the following scenarios:\n- Provider requested Provider-Health Plan Exchange using CDS-Hooks and SMART-on-FHIR\n- Member-authorized Health Plan to Health Plan exchange\n- Member-authorized Health Plan to Third-Party Application exchange\n\nThe latter two scenarios are provided to meet the requirements identified in the CMS Interoperability and Patient Access Final Rule.\n\n**There are items in this guide that are subject to update**. This includes:\n- Value Sets\n- Vocabularies (X12, NUBC etc.)\n- Examples\n\n**The Vocabulary, Value Sets and codings used to express data in this IG are subject to review and will be reconciled with**  [X12](http://www.x12.org).\n\nSee the [Table of Contents](toc.html) for more information.\n"
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.us.davinci-hrex: 1.0.0
  hl7.fhir.us.davinci-pas: 2.0.0
  hl7.fhir.us.davinci-atr: 2.0.0-ballot
  # hl7.fhir.us.ndh: 1.0.0-ballot
  # hl7.fhir.us.ndh: 0.1.0
  # hl7.fhir.us.directory-query: 1.0.0-ballot
  hl7.fhir.uv.extensions.r4: 1.0.0
parameters:
  show-inherited-invariants: false
  path-expansion-params: ../../input/expansion-params.json
# for using US ed of SNOMED
copyrightYear: 2020+
releaseLabel: STU2 # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
# category: Financial

extension:
  - url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
    valueCode: fm

pages:
  index.md:
    title: Home
  ImplementationGuide-hl7.fhir.us.davinci-pdex.md:
    title: PDex Implementation Guide
  overview.md:
    title: Overview
  introduction.md:
    title: Introduction
  securityandprivacy.md:
    title: Security and Privacy
  pdeximplementationactorsinteractionsdatapayloadsandmethods.md:
    title: PDex Implementation, Actors, Interactions, Data Payloads and Methods
    handlingdataprovenance.md:
      title: Handling Data Provenance
    payertopayerexchange.md:
      title: Payer-to-Payer Exchange (single member)
    datamapping.md:
      title: Data Mapping
      USCoreAllergyIntolerance.md:
        title: US Core AllergyIntolerance
      USCoreCarePlan.md:
        title: US Core CarePlan
      USCoreCareTeam.md:
        title: US Core CareTeam
      USCoreCondition.md:
        title: US Core Condition
      coverage.md:
        title: Coverage
      PdexDevice.md:
        title: PDex Device
      USCoreDiagnosticReportforLaboratoryResultsReporting.md:
        title: US Core DiagnosticReport for Laboratory Results Reporting
      USCoreDiagnosticReportforReportandNoteExchange.md:
        title: US Core DiagnosticReport for Report and Note Exchange
      USCoreDocumentReference.md:
        title: US Core DocumentReference
      USCoreEncounter.md:
        title: US Core Encounter
      USCoreGoal.md:
        title: US Core Goal
      USCoreImmunization.md:
        title: US Core Immunization
      USCoreImplantableDevice.md:
        title: US Core ImplantableDevice
      USCoreLaboratoryResultObservation.md:
        title: US Core Laboratory Result Observation
      USCoreLocation.md:
        title: US Core Location
      USCoreMedication.md:
        title: US Core Medication
      PDexMedicationDispense.md:
        title: PDex MedicationDispense
      USCoreMedicationRequest.md:
        title: US Core MedicationRequest
      USCoreOrganization.md:
        title: US Core Organization
      USCorePatient.md:
        title: US Core Patient
      USCorePediatricBMIforAgeObservation.md:
        title: US Core Pediatric BMI for Age Observation
      USCorePediatricHeadOccipital.md:
        title: US Core Pediatric Head Occipital-frontal Circumference Observation
      USCorePediatricWeightforHeightObservation.md:
        title: US Core Pediatric Weight for Height Observation
      USCorePractitioner.md:
        title: US Core Practitioner
      USCorePractitionerRole.md:
        title: US Core PractitionerRole
      PDexPriorAuthorization.md:
        title: PDex Prior Authorization
      USCoreProcedure.md:
        title: US Core Procedure
      PDexProvenance.md:
        title: PDex Provenance
      USCoreProvenance.md:
        title: US Core Provenance
      USCorePulseOximetry.md:
        title: US Core Pulse Oximetry
      USCoreSmokingStatusObservation.md:
        title: US Core Smoking Status Observation
      VitalSigns.md:
        title: VitalSigns
  usecasescenarios.md:
    title: Use Case Scenarios
  provider-controlledinformationrequestsandfiltering.md:
    title: Provider-controlled Information Requests and Filtering
  cds-hooks.md:
    title: CDS Hooks
    workflowexamples.md:
      title: Workflow Examples
  member-authorizedoauth2exchange.md:
    title: Member-Authorized OAuth2.0 Exchange
  changehistory.md:
    title: Change History
  credits.md:
    title: Credits
  downloads.md:
    title: Downloads
  artifacts.html:
    title: FHIR Artifacts
  other-igs.md:
    title: Other IG Artifacts

# ╭────────────────────────────────────────────menu.xml.ignore────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml.ignore file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  PDex IG Content: #pdeximplementationactorsinteractionsdatapayloadsandmethods.html
    Overview: overview.html
    Introduction: introduction.html
    Data Mapping: datamapping.html
    CDS Hooks: cds-hooks.html
    Payer-to-Payer: payertopayerexchange.html
    Change Log: changehistory.html
    Credits: credits.html
  FHIR Artifacts: artifacts.html
  Other IG Artifacts: other-igs.html
  Downloads: downloads.html
