	git add   input-cache/schemas/R5/fhir-single.xsd
	git add   input/davinci-pdex.json
	git rm    input/images/InteractionMethods1.png
	git rm    input/images/InteractionMethods2.png
	git rm    input/images/InteractionMethods3.png
	git rm    input/pagecontent/Actors.md
	git rm    input/pagecontent/AdditionalorModifiedHooks.md
	git add   input/pagecontent/CDS-Hooks.md
	git add   input/pagecontent/Coverage.md
	git add   input/pagecontent/Credits.md
	git add   input/pagecontent/DataMapping.md
	git rm    input/pagecontent/DataPayloads.md
	git rm    input/pagecontent/ExchangeInteractions.md
	git rm    input/pagecontent/FHIRProfilesandCDSHooksContext.md
	git rm    input/pagecontent/FirstVisitwithNewProvider.md
	git add   input/pagecontent/HandlingDataProvenance.md
	git rm    input/pagecontent/HookConfiguration.md
	git rm    input/pagecontent/InteractionMethods.md
	git rm    input/pagecontent/InteractionandPayloadMatrix.md
	git rm    input/pagecontent/MedicationDispense.md
	git add   input/pagecontent/Member-AuthorizedOAuth2Exchange.md
	git add   input/pagecontent/Overview.md
	git rm    input/pagecontent/PDexHooks.md
	git add   input/pagecontent/PDexImplementationActorsInteractionsDataPayloadsandMethods.md
	git rm    input/pagecontent/PatientPersona.md
	git add   input/pagecontent/Provider-controlledInformationRequestsandFiltering.md
	git rm    input/pagecontent/ReturnVisitwithProvider.md
	git rm    input/pagecontent/SupportforFHIRR4.md
	git rm    input/pagecontent/Systems.md
	git rm    input/pagecontent/Terminology.md
	git add   input/pagecontent/USCoreAllergyIntolerance.md
	git add   input/pagecontent/USCoreCarePlan.md
	git add   input/pagecontent/USCoreCareTeam.md
	git add   input/pagecontent/USCoreCondition.md
	git rm    input/pagecontent/USCoreDevice.md
	git rm    input/pagecontent/USCoreDiagnosticReport.md
	git add   input/pagecontent/USCoreDocumentReference.md
	git add   input/pagecontent/USCoreEncounter.md
	git add   input/pagecontent/USCoreImmunization.md
	git add   input/pagecontent/USCoreLocation.md
	git add   input/pagecontent/USCoreMedication.md
	git add   input/pagecontent/USCoreMedicationRequest.md
	git rm    input/pagecontent/USCoreObservation.md
	git add   input/pagecontent/USCoreOrganization.md
	git add   input/pagecontent/USCorePatient.md
	git add   input/pagecontent/USCorePractitioner.md
	git add   input/pagecontent/USCorePractitionerRole.md
	git add   input/pagecontent/USCoreProcedure.md
	git add   input/pagecontent/UseCaseScenarios.md
	git rm    input/pagecontent/UsefulPatientHistoryforProviders.md
	git add   input/pagecontent/WorkflowExamples.md

git add	input/pagecontent/Device.md
git add	input/pagecontent/HRexMedicationDispense.md
git add	input/pagecontent/PayerProvenance_.md
git add	input/pagecontent/USCoreDiagnosticReportforLaboratoryResultsReporting.md
git add	input/pagecontent/USCoreDiagnosticReportforReportandNoteExchange.md
git add	input/pagecontent/USCoreGoal_.md
git add	input/pagecontent/USCoreImplantableDevice.md
git add	input/pagecontent/USCorePediatricBMIforAgeObservation.md
git add	input/pagecontent/USCorePediatricWeightforHeightObservation.md
git add	input/pagecontent/USCoreProvenance_.md
git add	input/pagecontent/USCorePulseOximetry_.md
git add	input/pagecontent/USCoreSmokingStatusObservation_.md
git add	input/pagecontent/VitalSigns_.md
