	git add     output/CDS-Hooks.html
	git add     output/CapabilityStatement-us-core-server.html
	git add     output/CapabilityStatement-us-core-server.json.html
	git add     output/CapabilityStatement-us-core-server.ttl.html
	git add     output/CapabilityStatement-us-core-server.xml.html
	git add     output/Coverage.html
	git add     output/Credits.html
	git add     output/DataMapping.html
	git add     output/Device.html
	git add     output/HRexMedicationDispense.html
	git add     output/ImplementationGuide-hl7.fhir.us.davinci-pdex.json
	git add     output/ImplementationGuide-hl7.fhir.us.davinci-pdex.ttl
	git add     output/ImplementationGuide-hl7.fhir.us.davinci-pdex.xml
	git add     output/Introduction.html
	git add     output/Member-AuthorizedOAuth2Exchange.html
	git add     output/Overview.html
	git add     output/PDexImplementationActorsInteractionsDataPayloadsandMethods.html
	git add     output/PayerProvenance_.html
	git add     output/Provider-controlledInformationRequestsandFiltering.html
	git add     output/StructureDefinition-capabilitystatement-search-parameter-combination-definitions.html
	git add     output/StructureDefinition-capabilitystatement-search-parameter-combination-mappings.html
	git add     output/StructureDefinition-capabilitystatement-search-parameter-combination.html
	git add     output/StructureDefinition-capabilitystatement-search-parameter-combination.profile.json.html
	git add     output/StructureDefinition-capabilitystatement-search-parameter-combination.profile.ttl.html
	git add     output/StructureDefinition-capabilitystatement-search-parameter-combination.profile.xml.html
	git add     output/StructureDefinition-pdex-medicationdispense-definitions.html
	git add     output/StructureDefinition-pdex-medicationdispense-examples.html
	git add     output/StructureDefinition-pdex-medicationdispense-mappings.html
	git add     output/StructureDefinition-pdex-medicationdispense.html
	git add     output/StructureDefinition-pdex-medicationdispense.json
	git add     output/StructureDefinition-pdex-medicationdispense.json.html
	git add     output/StructureDefinition-pdex-medicationdispense.profile.json.html
	git add     output/StructureDefinition-pdex-medicationdispense.profile.ttl.html
	git add     output/StructureDefinition-pdex-medicationdispense.profile.xml.html
	git add     output/StructureDefinition-pdex-medicationdispense.ttl
	git add     output/StructureDefinition-pdex-medicationdispense.ttl.html
	git add     output/StructureDefinition-pdex-medicationdispense.xml
	git add     output/StructureDefinition-pdex-medicationdispense.xml.html
	git add     output/USCoreAllergyIntolerance.html
	git add     output/USCoreCarePlan.html
	git add     output/USCoreCareTeam.html
	git add     output/USCoreCondition.html
	git add     output/USCoreDiagnosticReportforLaboratoryResultsReporting.html
	git add     output/USCoreDiagnosticReportforReportandNoteExchange.html
	git add     output/USCoreDocumentReference.html
	git add     output/USCoreEncounter.html
	git add     output/USCoreGoal_.html
	git add     output/USCoreImmunization.html
	git add     output/USCoreImplantableDevice.html
	git add     output/USCoreLocation.html
	git add     output/USCoreMedication.html
	git add     output/USCoreMedicationRequest.html
	git add     output/USCoreOrganization.html
	git add     output/USCorePatient.html
	git add     output/USCorePediatricBMIforAgeObservation.html
	git add     output/USCorePediatricWeightforHeightObservation.html
	git add     output/USCorePractitioner.html
	git add     output/USCorePractitionerRole.html
	git add     output/USCoreProcedure.html
	git add     output/USCoreProvenance_.html
	git add     output/USCorePulseOximetry_.html
	git add     output/USCoreSmokingStatusObservation_.html
	git add     output/UseCaseScenarios.html
	git add     output/VitalSigns_.html
	git add     output/WorkflowExamples.html
	git add     output/artifacts.html
	git add     output/csvs.zip
	git add     output/definitions.json.zip
	git add     output/definitions.ttl.zip
	git add     output/definitions.xml.zip
	git add     output/examples.json.zip
	git add     output/examples.ttl.zip
	git add     output/examples.xml.zip
	git add     output/excels.zip
	git add     output/expansions.json
	git add     output/expansions.json.zip
	git add     output/expansions.xml
	git add     output/expansions.xml.zip
	git add     output/full-ig.zip
	git add     output/index.html
	git add     output/package.manifest.json
	git add     output/package.tgz
	git add     output/qa-tx.html
	git add     output/qa.html
	git add     output/qa.json
	git add     output/qa.txt
	git add     output/qa.xml
	git add     output/toc.html
	git add     output/validator-davinci-pdex.pack
	git add     output/validator.pack
	git add     template/onGenerate-ig-updated.xml
	git add     template/onGenerate-ig-working.1.xml
	git add     template/onGenerate-ig-working.json
	git add     template/onGenerate-ig-working.xml
