Instance: BundleWithProvenance
InstanceOf: Bundle
Description: "A bundle that returns provenance using _revinclude=Provenance:target"
* id = "3000002"
* meta.profile = "http://hl7.org/fhir/StructureDefinition/Bundle"
* type = http://hl7.org/fhir/bundle-type#searchset "Search Results"
* timestamp = "2020-09-28T23:26:23.217+00:00"
* total = 1
* link[0].relation = "self"
* link[0].url = "https://example.com/base/fhir/MedicationDispense?ct=W3sidG9rZW4iOiIrUklEOn53MThjQUk5RlVPZ0lEQUFBQUFBQU"
* entry[0].fullUrl = "https://example.com/base/MedicationDispense/1000001"
* entry[0].resource.resourceType = "MedicationDispense"
* entry[0].resource.id = "1000001"
* entry[0].resource.status = http://terminology.hl7.org/CodeSystem/medicationdispense-status#completed
* entry[0].resource.medicationCodeableConcept = $FDANationalDrugCodeCS#54458-872-10
* entry[0].resource.subject.reference = "Patient/1"
* entry[0].resource.performer.actor.reference = "Practitioner/4"
* entry[0].resource.location.reference = "Location/5"
* entry[0].resource.type =  http://terminology.hl7.org/CodeSystem/v3-ActCode#RF
* entry[0].resource.quantity.value = 60
* entry[0].resource.daysSupply.value = 30
* entry[0].search.mode = http://hl7.org/fhir/search-entry-mode#match
* entry[1].fullUrl = "https://example.com/base/Provenance/321000001"
* entry[1].resource.resourceType = "Provenance"
* entry[1].resource.id = "321000001"
* entry[1].resource.meta.versionId = "1"
* entry[1].resource.meta.lastUpdated = "2020-09-28T23:26:23.217+00:00"
* entry[1].resource.meta.profile = "http://hl7.org/fhir/us/davinci-pdex/StructureDefinition/pdex-provenance"
* entry[1].resource.target[0].reference = "MedicationDispense/1000001"
* entry[1].resource.recorded = "2020-07-12T18:26:23.217+00:00"
* entry[1].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[1].resource.agent[0].who.reference = "Organization/Payer1"
* entry[1].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[1].resource.entity.what.display = "No reference available"
* entry[1].resource.entity.extension.url = "http://hl7.org/fhir/us/davinci-pdex/StructureDefinition/ProvenanceSourceFrom"
* entry[1].resource.entity.extension.valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[1].search.mode = http://hl7.org/fhir/search-entry-mode#include


Instance: BundleConditionWithProvenance
InstanceOf: Bundle
Description: "A bundle that returns Conditions with provenance using _revinclude=Provenance:target"
* id = "3000003"
* meta.profile = "http://hl7.org/fhir/StructureDefinition/Bundle"
* type = http://hl7.org/fhir/bundle-type#searchset "Search Results"
* timestamp = "2020-09-28T23:26:23.217+00:00"
* total = 2
* entry[0].fullUrl = "https://example.com/base/Condition/101"
* entry[0].resource.resourceType = "Condition"
* entry[0].resource.id = "101"
* entry[0].resource.clinicalStatus = http://terminology.hl7.org/CodeSystem/condition-clinical#active
* entry[0].resource.verificationStatus = http://terminology.hl7.org/CodeSystem/condition-ver-status#confirmed
* entry[0].resource.category = http://terminology.hl7.org/CodeSystem/condition-category#problem-list-item
* entry[0].resource.code = http://snomed.info/sct#442311008 "liveborn born in hospital"
* entry[0].resource.subject.reference = "Patient/1"
* entry[0].resource.onsetDateTime = "1995-09-20"
* entry[0].search.mode = http://hl7.org/fhir/search-entry-mode#match
* entry[1].fullUrl = "https://example.com/base/Condition/102"
* entry[1].resource.resourceType = "Condition"
* entry[1].resource.id = "102"
* entry[1].resource.clinicalStatus = http://terminology.hl7.org/CodeSystem/condition-clinical#active
* entry[1].resource.verificationStatus = http://terminology.hl7.org/CodeSystem/condition-ver-status#confirmed
* entry[1].resource.category = http://terminology.hl7.org/CodeSystem/condition-category#health-concern
* entry[1].resource.code = http://snomed.info/sct#247824007 "Fear of becoming fat"
* entry[1].resource.subject.reference = "Patient/1"
* entry[1].resource.onsetDateTime = "2020-03-13"
* entry[1].search.mode = http://hl7.org/fhir/search-entry-mode#match
* entry[2].fullUrl = "https://example.com/base/Provenance/3101"
* entry[2].resource.resourceType = "Provenance"
* entry[2].resource.id = "3101"
* entry[2].resource.meta.versionId = "1"
* entry[2].resource.meta.lastUpdated = "2020-09-28T23:26:23.217+00:00"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/us/davinci-pdex/StructureDefinition/pdex-provenance"
* entry[2].resource.target[0].reference = "Condition/101"
* entry[2].resource.recorded = "1995-09-20T18:26:23.217+00:00"
* entry[2].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#author "Author"
* entry[2].resource.agent[0].who.reference = "Organization/ProviderOrg2"
* entry[2].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[2].resource.entity.what.display = "No reference available"
* entry[2].resource.entity.extension.url = "http://hl7.org/fhir/us/davinci-pdex/StructureDefinition/ProvenanceSourceFrom"
* entry[2].resource.entity.extension.valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[2].search.mode = http://hl7.org/fhir/search-entry-mode#match



Instance: BundleExamplePayer1
InstanceOf: Bundle
Description: "The bundle pulled from Payer1 by Payer 2 when a member switches to Payer 2. Patient, 2 Encounters and 2 Provenance records."
* id = "1000000-1"
* meta.profile = "http://hl7.org/fhir/StructureDefinition/Bundle"
* type = http://hl7.org/fhir/bundle-type#searchset "Search Results"
* timestamp = "2019-12-31T20:26:23.217+00:00"
* total = 3
* entry[0].fullUrl = "https://example.com/base/Patient/1"
* entry[0].resource.resourceType = "Patient"
* entry[0].resource.id = "1"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
* entry[0].resource.meta.lastUpdated = "2019-07-07T13:26:22.0314215+00:00"
* entry[0].resource.language = #en-US
* entry[0].resource.active = true
* entry[0].resource.name[0].family = "Appleseed"
* entry[0].resource.name[0].given[0] = "Johnny"
* entry[0].resource.telecom[0].system = http://hl7.org/fhir/contact-point-system#phone
* entry[0].resource.telecom[0].value = "(443)555-1212"
* entry[0].resource.telecom[0].rank = 1
* entry[0].resource.telecom[1].system = http://hl7.org/fhir/contact-point-system#phone
* entry[0].resource.telecom[1].value = "(410)678-2323"
* entry[0].resource.telecom[1].rank = 2
* entry[0].resource.gender = http://hl7.org/fhir/administrative-gender#male
* entry[0].resource.birthDate = "1986-01-01"
* entry[0].resource.address[0].type = http://hl7.org/fhir/address-type#physical
* entry[0].resource.address[0].line[0] = "123 Main Street"
* entry[0].resource.address[0].city = "Pittsburgh"
* entry[0].resource.address[0].state = "PA"
* entry[0].resource.address[0].postalCode = "12519"
* entry[0].resource.maritalStatus = http://terminology.hl7.org/CodeSystem/v3-NullFlavor#UNK
* entry[0].resource.identifier[0].type = http://terminology.hl7.org/CodeSystem/v2-0203#MB
* entry[0].resource.identifier[0].value = "https://www.xxxhealthplan.com/fhir/memberidentifier#1234-234-1243-12345678901"
* entry[0].resource.identifier[0].system = "https://www.xxxhealthplan.com/fhir/memberidentifier"
* entry[0].resource.identifier[1].type = http://terminology.hl7.org/CodeSystem/v2-0203#MR
* entry[0].resource.identifier[1].value = "1234-234-1243-12345678901m"
* entry[0].resource.identifier[1].system = "https://www.xxxhealthplan.com/fhir/medicalrecordnumber"
* entry[0].resource.identifier[2].type = http://terminology.hl7.org/CodeSystem/v2-0203#XV
* entry[0].resource.identifier[2].value = "1234-234-1243-12345678901u"
* entry[0].resource.identifier[2].system = "https://www.xxxhealthplan.com/fhir/uniquememberidentifier"
* entry[0].resource.identifier[3].type = http://terminology.hl7.org/CodeSystem/v2-0203#PT
* entry[0].resource.identifier[3].value = "1234-234-1243-12345678901a"
* entry[0].resource.identifier[3].system = "https://www.xxxhealthplan.com/fhir/patacctnum"
* entry[1].fullUrl = "https://example.com/base/Encounter/6-1"
* entry[1].resource.resourceType = "Encounter"
* entry[1].resource.id = "6-1"
* entry[1].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[1].resource.meta.lastUpdated = "2019-07-14T19:26:23.217+00:00"
* entry[1].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[1].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[1].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[1].resource.subject.reference = "Patient/1"
* entry[2].fullUrl = "https://example.com/base/Encounter/7-1"
* entry[2].resource.resourceType = "Encounter"
* entry[2].resource.id = "7-1"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[2].resource.meta.lastUpdated = "2019-10-15T20:26:23.217+00:00"
* entry[2].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[2].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[2].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[2].resource.subject.reference = "Patient/1"
* entry[3].fullUrl = "https://example.com/base/Provenance/1000002-1"
* entry[3].resource.resourceType = "Provenance"
* entry[3].resource.id = "1000002-1"
* entry[3].resource.meta.versionId = "1"
* entry[3].resource.meta.profile = $PdexProvenance
* entry[3].resource.meta.lastUpdated = "2019-07-14T19:26:23.217+00:00"
* entry[3].resource.target[0].reference = "https://example.com/base/Encounter/6-1"
* entry[3].resource.recorded = "2020-07-10T16:26:23.217+00:00"
* entry[3].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[3].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[3].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[3].resource.entity.what.display = "No reference available"
* entry[3].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[4].fullUrl = "https://example.com/base/Provenance/1000003-1"
* entry[4].resource.resourceType = "Provenance"
* entry[4].resource.id = "1000003-1"
* entry[4].resource.meta.versionId = "1"
* entry[4].resource.meta.lastUpdated = "2019-10-15T20:26:23.217+00:00"
* entry[4].resource.target[0].reference = "Encounter/7-1"
* entry[4].resource.recorded = "2020-07-10T16:26:23.217+00:00"
* entry[4].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[4].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[4].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[4].resource.entity.what.display = "No reference available"
* entry[4].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[5].fullUrl = "https://example.com/base/Provenance/1000004-1"
* entry[5].resource.resourceType = "Provenance"
* entry[5].resource.id = "1000004-1"
* entry[5].resource.meta.versionId = "1"
* entry[5].resource.meta.lastUpdated = "2019-12-31T20:26:23.217+00:00"
* entry[5].resource.target[0].reference = "Bundle/1000000-1"
* entry[5].resource.recorded = "2019-12-31T20:26:23.217+00:00"
* entry[5].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[5].resource.agent[0].who.reference = "Organization/Payer1"
* entry[5].resource.agent[0].role.coding = http://terminology.hl7.org/CodeSystem/contractsignertypecodes#TRANS

Instance: BundleExamplePayer2
InstanceOf: Bundle
Description: "The bundle pulled from Payer2 by Payer 3 when a member switches to Payer 3. Patient, 2 Encounters and 2 Provenance records plus new records from Payer 2."
* id = "1000000-2"
* meta.profile = "http://hl7.org/fhir/StructureDefinition/Bundle"
* type = http://hl7.org/fhir/bundle-type#searchset "Search Results"
* timestamp = "2019-12-31T20:26:23.217+00:00"
* total = 4
* entry[0].fullUrl = "https://example.com/base/Patient/1-2"
* entry[0].resource.resourceType = "Patient"
* entry[0].resource.id = "1-2"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
* entry[0].resource.meta.lastUpdated = "2019-07-07T13:26:22.0314215+00:00"
* entry[0].resource.language = #en-US
* entry[0].resource.active = true
* entry[0].resource.name[0].family = "Appleseed"
* entry[0].resource.name[0].given[0] = "Johnny"
* entry[0].resource.telecom[0].system = http://hl7.org/fhir/contact-point-system#phone
* entry[0].resource.telecom[0].value = "(443)555-1212"
* entry[0].resource.telecom[0].rank = 1
* entry[0].resource.telecom[1].system = http://hl7.org/fhir/contact-point-system#phone
* entry[0].resource.telecom[1].value = "(410)678-2323"
* entry[0].resource.telecom[1].rank = 2
* entry[0].resource.gender = http://hl7.org/fhir/administrative-gender#male
* entry[0].resource.birthDate = "1986-01-01"
* entry[0].resource.address[0].type = http://hl7.org/fhir/address-type#physical
* entry[0].resource.address[0].line[0] = "123 Main Street"
* entry[0].resource.address[0].city = "Pittsburgh"
* entry[0].resource.address[0].state = "PA"
* entry[0].resource.address[0].postalCode = "12519"
* entry[0].resource.maritalStatus = http://terminology.hl7.org/CodeSystem/v3-NullFlavor#UNK
* entry[0].resource.identifier[0].type = http://terminology.hl7.org/CodeSystem/v2-0203#MB
* entry[0].resource.identifier[0].value = "https://www.xxxhealthplan.com/fhir/memberidentifier#1234-234-1243-12345678901"
* entry[0].resource.identifier[0].system = "https://www.xxxhealthplan.com/fhir/memberidentifier"
* entry[0].resource.identifier[1].type = http://terminology.hl7.org/CodeSystem/v2-0203#MR
* entry[0].resource.identifier[1].value = "1234-234-1243-12345678901m"
* entry[0].resource.identifier[1].system = "https://www.xxxhealthplan.com/fhir/medicalrecordnumber"
* entry[0].resource.identifier[2].type = http://terminology.hl7.org/CodeSystem/v2-0203#XV
* entry[0].resource.identifier[2].value = "1234-234-1243-12345678901u"
* entry[0].resource.identifier[2].system = "https://www.xxxhealthplan.com/fhir/uniquememberidentifier"
* entry[0].resource.identifier[3].type = http://terminology.hl7.org/CodeSystem/v2-0203#PT
* entry[0].resource.identifier[3].value = "1234-234-1243-12345678901a"
* entry[0].resource.identifier[3].system = "https://www.xxxhealthplan.com/fhir/patacctnum"
* entry[1].fullUrl = "https://example.com/base/Encounter/6-1-2"
* entry[1].resource.resourceType = "Encounter"
* entry[1].resource.id = "6-1-2"
* entry[1].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[1].resource.meta.lastUpdated = "2019-07-14T19:26:23.217+00:00"
* entry[1].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[1].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[1].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[1].resource.subject.reference = "Patient/1-2"
* entry[2].fullUrl = "https://example.com/base/Encounter/7-1-2"
* entry[2].resource.resourceType = "Encounter"
* entry[2].resource.id = "7-1-2"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[2].resource.meta.lastUpdated = "2019-10-15T20:26:23.217+00:00"
* entry[2].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[2].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[2].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[2].resource.subject.reference = "Patient/1-2"
* entry[3].fullUrl = "https://example.com/base/Encounter/8-2"
* entry[3].resource.resourceType = "Encounter"
* entry[3].resource.id = "8-2"
* entry[3].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[3].resource.meta.lastUpdated = "2020-06-15T20:26:23.217+00:00"
* entry[3].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[3].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[3].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[3].resource.subject.reference = "Patient/1-2"
* entry[4].fullUrl = "https://example.com/base/Provenance/1000002-1-2"
* entry[4].resource.resourceType = "Provenance"
* entry[4].resource.id = "1000002-1-2"
* entry[4].resource.meta.versionId = "1"
* entry[4].resource.meta.profile = $PdexProvenance
* entry[4].resource.meta.lastUpdated = "2019-07-14T19:26:23.217+00:00"
* entry[4].resource.target[0].reference = "https://example.com/base/Encounter/6-1-2"
* entry[4].resource.recorded = "2020-07-10T16:26:23.217+00:00"
* entry[4].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[4].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[4].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[4].resource.entity.what.display = "No reference available"
* entry[4].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[5].fullUrl = "https://example.com/base/Provenance/1000003-1-2"
* entry[5].resource.resourceType = "Provenance"
* entry[5].resource.id = "1000003-1-2"
* entry[5].resource.meta.versionId = "1"
* entry[5].resource.meta.lastUpdated = "2019-10-15T20:26:23.217+00:00"
* entry[5].resource.target[0].reference = "Encounter/7-1-2"
* entry[5].resource.recorded = "2020-07-10T16:26:23.217+00:00"
* entry[5].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[5].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[5].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[5].resource.entity.what.display = "No reference available"
* entry[5].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[6].fullUrl = "https://example.com/base/Provenance/1000004-1-2"
* entry[6].resource.resourceType = "Provenance"
* entry[6].resource.id = "1000004-1-2"
* entry[6].resource.meta.versionId = "1"
* entry[6].resource.meta.lastUpdated = "2019-12-31T20:26:23.217+00:00"
* entry[6].resource.target[0].reference = "Patient/1-2"
* entry[6].resource.target[1].reference = "Encounter/6-1-2"
* entry[6].resource.target[2].reference = "Encounter/7-1-2"
* entry[6].resource.target[3].reference = "Provenance/1000002-1-2"
* entry[6].resource.target[4].reference = "Provenance/1000003-1-2"
* entry[6].resource.recorded = "2019-12-31T20:26:23.217+00:00"
* entry[6].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[6].resource.agent[0].who.reference = "Organization/Payer1"
* entry[6].resource.agent[0].role.coding = http://terminology.hl7.org/CodeSystem/contractsignertypecodes#TRANS
* entry[7].fullUrl = "https://example.com/base/Provenance/1000004-2"
* entry[7].resource.resourceType = "Provenance"
* entry[7].resource.id = "1000004-2"
* entry[7].resource.meta.versionId = "1"
* entry[7].resource.meta.lastUpdated = "2020-06-15T20:26:23.217+00:00"
* entry[7].resource.target[0].reference = "Encounter/8-2"
* entry[7].resource.recorded = "2020-06-15T20:26:23.217+00:00"
* entry[7].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[7].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[7].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[7].resource.entity.what.display = "No reference available"
* entry[7].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[8].fullUrl = "https://example.com/base/Provenance/1000005-2"
* entry[8].resource.resourceType = "Provenance"
* entry[8].resource.id = "1000004-2"
* entry[8].resource.meta.versionId = "1"
* entry[8].resource.meta.lastUpdated = "2020-12-31T20:26:23.217+00:00"
* entry[8].resource.target[0].reference = "Bundle/1000000-2"
* entry[8].resource.recorded = "2019-12-31T20:26:23.217+00:00"
* entry[8].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[8].resource.agent[0].who.reference = "Organization/Payer1"
* entry[8].resource.agent[0].role.coding = http://terminology.hl7.org/CodeSystem/contractsignertypecodes#TRANS


Instance: BundleExamplePayer3
InstanceOf: Bundle
Description: "The bundle pulled from Payer3 by Payer 4 when a member switches to Payer 4. Patient, 2 Encounters and 2 Provenance records originating from Payer 1 plus new records from Payer 2 and Payer 3, including supporting Provenance records."
* id = "1000000-3"
* meta.profile = "http://hl7.org/fhir/StructureDefinition/Bundle"
* type = http://hl7.org/fhir/bundle-type#searchset "Search Results"
* timestamp = "2021-12-31T20:26:23.217+00:00"
* total = 5
* entry[0].fullUrl = "https://example.com/base/Patient/1-3"
* entry[0].resource.resourceType = "Patient"
* entry[0].resource.id = "1-3"
* entry[0].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
* entry[0].resource.meta.lastUpdated = "2021-01-07T13:26:22.0314215+00:00"
* entry[0].resource.language = #en-US
* entry[0].resource.active = true
* entry[0].resource.name[0].family = "Appleseed"
* entry[0].resource.name[0].given[0] = "Johnny"
* entry[0].resource.telecom[0].system = http://hl7.org/fhir/contact-point-system#phone
* entry[0].resource.telecom[0].value = "(443)555-1212"
* entry[0].resource.telecom[0].rank = 1
* entry[0].resource.telecom[1].system = http://hl7.org/fhir/contact-point-system#phone
* entry[0].resource.telecom[1].value = "(410)678-2323"
* entry[0].resource.telecom[1].rank = 2
* entry[0].resource.gender = http://hl7.org/fhir/administrative-gender#male
* entry[0].resource.birthDate = "1986-01-01"
* entry[0].resource.address[0].type = http://hl7.org/fhir/address-type#physical
* entry[0].resource.address[0].line[0] = "123 Main Street"
* entry[0].resource.address[0].city = "Pittsburgh"
* entry[0].resource.address[0].state = "PA"
* entry[0].resource.address[0].postalCode = "12519"
* entry[0].resource.maritalStatus = http://terminology.hl7.org/CodeSystem/v3-NullFlavor#UNK
* entry[0].resource.identifier[0].type = http://terminology.hl7.org/CodeSystem/v2-0203#MB
* entry[0].resource.identifier[0].value = "https://www.xxxhealthplan.com/fhir/memberidentifier#1234-234-1243-12345678901"
* entry[0].resource.identifier[0].system = "https://www.xxxhealthplan.com/fhir/memberidentifier"
* entry[0].resource.identifier[1].type = http://terminology.hl7.org/CodeSystem/v2-0203#MR
* entry[0].resource.identifier[1].value = "1234-234-1243-12345678901m"
* entry[0].resource.identifier[1].system = "https://www.xxxhealthplan.com/fhir/medicalrecordnumber"
* entry[0].resource.identifier[2].type = http://terminology.hl7.org/CodeSystem/v2-0203#XV
* entry[0].resource.identifier[2].value = "1234-234-1243-12345678901u"
* entry[0].resource.identifier[2].system = "https://www.xxxhealthplan.com/fhir/uniquememberidentifier"
* entry[0].resource.identifier[3].type = http://terminology.hl7.org/CodeSystem/v2-0203#PT
* entry[0].resource.identifier[3].value = "1234-234-1243-12345678901a"
* entry[0].resource.identifier[3].system = "https://www.xxxhealthplan.com/fhir/patacctnum"
* entry[1].fullUrl = "https://example.com/base/Encounter/6-1-2-3"
* entry[1].resource.resourceType = "Encounter"
* entry[1].resource.id = "6-1-2-3"
* entry[1].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[1].resource.meta.lastUpdated = "2021-01-14T19:26:23.217+00:00"
* entry[1].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[1].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[1].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[1].resource.subject.reference = "Patient/1-2"
* entry[2].fullUrl = "https://example.com/base/Encounter/7-1-2-3"
* entry[2].resource.resourceType = "Encounter"
* entry[2].resource.id = "7-1-2-3"
* entry[2].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[2].resource.meta.lastUpdated = "2021-01-15T20:26:23.217+00:00"
* entry[2].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[2].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[2].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[2].resource.subject.reference = "Patient/1-3"
* entry[3].fullUrl = "https://example.com/base/Encounter/8-2-3"
* entry[3].resource.resourceType = "Encounter"
* entry[3].resource.id = "8-2-3"
* entry[3].resource.meta.profile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"
* entry[3].resource.meta.lastUpdated = "2021-03-15T20:26:23.217+00:00"
* entry[3].resource.status = http://hl7.org/fhir/encounter-status#finished "Finished"
* entry[3].resource.class =  http://terminology.hl7.org/CodeSystem/v3-ActCode#AMB "Ambulatory"
* entry[3].resource.type =  $SnomedCT#11429006 "Consultation"
* entry[3].resource.subject.reference = "Patient/1-3"
* entry[4].fullUrl = "https://example.com/base/Provenance/1000002-1-2-3"
* entry[4].resource.resourceType = "Provenance"
* entry[4].resource.id = "1000002-1-2-3"
* entry[4].resource.meta.versionId = "1"
* entry[4].resource.meta.profile = $PdexProvenance
* entry[4].resource.meta.lastUpdated = "2021-01-14T19:26:23.217+00:00"
* entry[4].resource.target[0].reference = "https://example.com/base/Encounter/6-1-2-3"
* entry[4].resource.recorded = "2020-07-10T16:26:23.217+00:00"
* entry[4].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[4].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[4].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[4].resource.entity.what.display = "No reference available"
* entry[4].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[5].fullUrl = "https://example.com/base/Provenance/1000003-1-2-3"
* entry[5].resource.resourceType = "Provenance"
* entry[5].resource.id = "1000003-1-2-3"
* entry[5].resource.meta.versionId = "1"
* entry[5].resource.meta.lastUpdated = "2021-10-01T20:26:23.217+00:00"
* entry[5].resource.target[0].reference = "Encounter/7-1-2-3"
* entry[5].resource.recorded = "2020-07-10T16:26:23.217+00:00"
* entry[5].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[5].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[5].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[5].resource.entity.what.display = "No reference available"
* entry[5].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[6].fullUrl = "https://example.com/base/Provenance/1000005-2"
* entry[6].resource.resourceType = "Provenance"
* entry[6].resource.id = "1000005-2"
* entry[6].resource.meta.versionId = "1"
* entry[6].resource.meta.lastUpdated = "2021-10-01T20:26:23.217+00:00"
* entry[6].resource.target[0].reference = "Encounter/8-2-3"
* entry[6].resource.recorded = "2021-03-10T16:26:23.217+00:00"
* entry[6].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[6].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[6].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[6].resource.entity.what.display = "No reference available"
* entry[6].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[7].fullUrl = "https://example.com/base/Provenance/1000004-1-2-3"
* entry[7].resource.resourceType = "Provenance"
* entry[7].resource.id = "1000004-1-2-3"
* entry[7].resource.meta.versionId = "1"
* entry[7].resource.meta.lastUpdated = "2019-12-31T20:26:23.217+00:00"
* entry[7].resource.target[0].reference = "Patient/1-3"
* entry[7].resource.target[1].reference = "Encounter/6-1-2-3"
* entry[7].resource.target[2].reference = "Encounter/7-1-2-3"
* entry[7].resource.target[3].reference = "Provenance/1000002-1-2-3"
* entry[7].resource.target[4].reference = "Provenance/1000003-1-2-3"
* entry[7].resource.recorded = "2019-12-31T20:26:23.217+00:00"
* entry[7].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[7].resource.agent[0].who.reference = "Organization/Payer1"
* entry[7].resource.agent[0].role.coding = http://terminology.hl7.org/CodeSystem/contractsignertypecodes#TRANS
* entry[8].fullUrl = "https://example.com/base/Provenance/1000004-2"
* entry[8].resource.resourceType = "Provenance"
* entry[8].resource.id = "1000004-2"
* entry[8].resource.meta.versionId = "1"
* entry[8].resource.meta.lastUpdated = "2020-06-15T20:26:23.217+00:00"
* entry[8].resource.target[0].reference = "Encounter/8-2-3"
* entry[8].resource.target[1].reference = "Provenance/8-2-3"
* entry[8].resource.recorded = "2020-06-15T20:26:23.217+00:00"
* entry[8].resource.agent[0].type = http://terminology.hl7.org/CodeSystem/provenance-participant-type#author "Author"
* entry[8].resource.agent[0].who.reference = "Organization/ProviderOrg1"
* entry[8].resource.entity.role = http://hl7.org/fhir/provenance-entity-role#source
* entry[8].resource.entity.what.display = "No reference available"
* entry[8].resource.entity.extension[sourceFormat].valueCodeableConcept = http://hl7.org/fhir/us/davinci-pdex/CodeSystem/ProvenancePayerDataSource#hl7ccda "HL7 C-CDA"
* entry[9].fullUrl = "https://example.com/base/Provenance/1000005-2"
* entry[9].resource.resourceType = "Provenance"
* entry[9].resource.id = "1000004-2"
* entry[9].resource.meta.versionId = "1"
* entry[9].resource.meta.lastUpdated = "2020-12-31T20:26:23.217+00:00"
* entry[9].resource.target[0].reference = "Bundle/1000000-2"
* entry[9].resource.recorded = "2019-12-31T20:26:23.217+00:00"
* entry[9].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[9].resource.agent[0].who.reference = "Organization/Payer1"
* entry[9].resource.agent[0].role.coding = http://terminology.hl7.org/CodeSystem/contractsignertypecodes#TRANS
* entry[10].fullUrl = "https://example.com/base/Provenance/1000006-3"
* entry[10].resource.resourceType = "Provenance"
* entry[10].resource.id = "1000006-3"
* entry[10].resource.meta.versionId = "1"
* entry[10].resource.meta.lastUpdated = "2020-12-31T20:26:23.217+00:00"
* entry[10].resource.target[0].reference = "Bundle/1000000-2"
* entry[10].resource.recorded = "2019-12-31T20:26:23.217+00:00"
* entry[10].resource.agent[0].type = http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type#transmitter "Transmitter"
* entry[10].resource.agent[0].who.reference = "Organization/Payer1"
* entry[10].resource.agent[0].role.coding = http://terminology.hl7.org/CodeSystem/contractsignertypecodes#TRANS

