@startuml
skinparam svgDimensionStyle false

participant "Payer2 | New Payer | Requesting Payer" as Payer2
participant "Payer1 | Old Payer | Receiving Payer" as Payer1
participant "Payer Directory | Certificate Authority" as PayerDirectory

== Data Requests ==
group #Pink Step 3: Request NON-SCOPED Access token
	Payer2 -> Payer1 : **16** Use OAuth2.0 token endpoint to \nrequest access
  note right #LightGrey
  	Client Credentials used to obtain token.
  	Token is NOT scoped to Patient/Member.
  endnote
  Payer1 -> Payer2 : **17** Return access token

end

group #Pink Step 4: Exchange PDex (USCDI) Information via API
  Payer2 -> Payer1 : **18** Use NON-SCOPED access token to access API
	Payer1 -> Payer2 : **19** Return $everything-pdex or \nincremental data as appropriate/supported \nby Payer1 Capability Statement
  note right #LightGrey
  	When a NON-SCOPED access token is provided each query to
    a resource endpoint will need to perform a consent query
    to confirm that access is permitted.

    This control **could** be performed by implementing a custom function.
    The function would perform the consent validation and then retrieve
    the relevant data and return to Payer2.
  endnote
end
@enduml
